/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface IssuerInterface extends utils.Interface {
  functions: {
    "couponContract()": FunctionFragment;
    "currentPrice(address)": FunctionFragment;
    "issue(address,uint256,address)": FunctionFragment;
    "lockupConfig()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setCouponContract(address)": FunctionFragment;
    "setDependencies(address,address)": FunctionFragment;
    "setLimits(uint256,uint256,uint256,uint256)": FunctionFragment;
    "setTokenInfo(address,bool,bool,uint256)": FunctionFragment;
    "setTokensInfo(address[],bool[],bool[],uint256[])": FunctionFragment;
    "stream()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "whitelist(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "couponContract"
      | "currentPrice"
      | "issue"
      | "lockupConfig"
      | "owner"
      | "renounceOwnership"
      | "setCouponContract"
      | "setDependencies"
      | "setLimits"
      | "setTokenInfo"
      | "setTokensInfo"
      | "stream"
      | "transferOwnership"
      | "whitelist"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "couponContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentPrice",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "issue",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "lockupConfig",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCouponContract",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setDependencies",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setLimits",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenInfo",
    values: [string, boolean, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokensInfo",
    values: [string[], boolean[], boolean[], BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "stream", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "whitelist", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "couponContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "issue", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lockupConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCouponContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDependencies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setLimits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTokenInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokensInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stream", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "whitelist", data: BytesLike): Result;

  events: {
    "CouponsIssued(address,address,uint256,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "TokenWhitelisted(address,bool,bool,uint256)": EventFragment;
    "TokensWhiteListed(address[],bool[],uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CouponsIssued"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenWhitelisted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokensWhiteListed"): EventFragment;
}

export interface CouponsIssuedEventObject {
  user: string;
  token: string;
  amount: BigNumber;
  coupons: BigNumber;
}
export type CouponsIssuedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  CouponsIssuedEventObject
>;

export type CouponsIssuedEventFilter = TypedEventFilter<CouponsIssuedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface TokenWhitelistedEventObject {
  token: string;
  enabled: boolean;
  burnable: boolean;
  teraCouponPerToken: BigNumber;
}
export type TokenWhitelistedEvent = TypedEvent<
  [string, boolean, boolean, BigNumber],
  TokenWhitelistedEventObject
>;

export type TokenWhitelistedEventFilter =
  TypedEventFilter<TokenWhitelistedEvent>;

export interface TokensWhiteListedEventObject {
  tokens: string[];
  burnable: boolean[];
  timestamp: BigNumber;
}
export type TokensWhiteListedEvent = TypedEvent<
  [string[], boolean[], BigNumber],
  TokensWhiteListedEventObject
>;

export type TokensWhiteListedEventFilter =
  TypedEventFilter<TokensWhiteListedEvent>;

export interface Issuer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IssuerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    couponContract(overrides?: CallOverrides): Promise<[string]>;

    currentPrice(
      token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { teraCouponPerToken: BigNumber }>;

    issue(
      inputToken: string,
      amount: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    lockupConfig(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        threshold_size: BigNumber;
        days_multiple: BigNumber;
        offset: BigNumber;
      }
    >;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setCouponContract(
      newCouponAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setDependencies(
      couponAddress: string,
      hedgeyAdapterAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setLimits(
      threshold_size: BigNumberish,
      days_multiple: BigNumberish,
      offset: BigNumberish,
      _targetedMintsPerWeek: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setTokenInfo(
      token: string,
      enabled: boolean,
      burnable: boolean,
      startingRate: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setTokensInfo(
      tokens: string[],
      enabled: boolean[],
      burnable: boolean[],
      startingRate: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    stream(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    whitelist(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [boolean, boolean, BigNumber, BigNumber] & {
        enabled: boolean;
        burnable: boolean;
        lastminted_timestamp: BigNumber;
        teraCouponPerTokenPerSecond: BigNumber;
      }
    >;
  };

  couponContract(overrides?: CallOverrides): Promise<string>;

  currentPrice(token: string, overrides?: CallOverrides): Promise<BigNumber>;

  issue(
    inputToken: string,
    amount: BigNumberish,
    recipient: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  lockupConfig(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      threshold_size: BigNumber;
      days_multiple: BigNumber;
      offset: BigNumber;
    }
  >;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setCouponContract(
    newCouponAddress: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setDependencies(
    couponAddress: string,
    hedgeyAdapterAddress: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setLimits(
    threshold_size: BigNumberish,
    days_multiple: BigNumberish,
    offset: BigNumberish,
    _targetedMintsPerWeek: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setTokenInfo(
    token: string,
    enabled: boolean,
    burnable: boolean,
    startingRate: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setTokensInfo(
    tokens: string[],
    enabled: boolean[],
    burnable: boolean[],
    startingRate: BigNumberish[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  stream(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  whitelist(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [boolean, boolean, BigNumber, BigNumber] & {
      enabled: boolean;
      burnable: boolean;
      lastminted_timestamp: BigNumber;
      teraCouponPerTokenPerSecond: BigNumber;
    }
  >;

  callStatic: {
    couponContract(overrides?: CallOverrides): Promise<string>;

    currentPrice(token: string, overrides?: CallOverrides): Promise<BigNumber>;

    issue(
      inputToken: string,
      amount: BigNumberish,
      recipient: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lockupConfig(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        threshold_size: BigNumber;
        days_multiple: BigNumber;
        offset: BigNumber;
      }
    >;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setCouponContract(
      newCouponAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setDependencies(
      couponAddress: string,
      hedgeyAdapterAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setLimits(
      threshold_size: BigNumberish,
      days_multiple: BigNumberish,
      offset: BigNumberish,
      _targetedMintsPerWeek: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setTokenInfo(
      token: string,
      enabled: boolean,
      burnable: boolean,
      startingRate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setTokensInfo(
      tokens: string[],
      enabled: boolean[],
      burnable: boolean[],
      startingRate: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    stream(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    whitelist(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [boolean, boolean, BigNumber, BigNumber] & {
        enabled: boolean;
        burnable: boolean;
        lastminted_timestamp: BigNumber;
        teraCouponPerTokenPerSecond: BigNumber;
      }
    >;
  };

  filters: {
    "CouponsIssued(address,address,uint256,uint256)"(
      user?: string | null,
      token?: string | null,
      amount?: null,
      coupons?: null
    ): CouponsIssuedEventFilter;
    CouponsIssued(
      user?: string | null,
      token?: string | null,
      amount?: null,
      coupons?: null
    ): CouponsIssuedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "TokenWhitelisted(address,bool,bool,uint256)"(
      token?: null,
      enabled?: null,
      burnable?: null,
      teraCouponPerToken?: null
    ): TokenWhitelistedEventFilter;
    TokenWhitelisted(
      token?: null,
      enabled?: null,
      burnable?: null,
      teraCouponPerToken?: null
    ): TokenWhitelistedEventFilter;

    "TokensWhiteListed(address[],bool[],uint256)"(
      tokens?: null,
      burnable?: null,
      timestamp?: null
    ): TokensWhiteListedEventFilter;
    TokensWhiteListed(
      tokens?: null,
      burnable?: null,
      timestamp?: null
    ): TokensWhiteListedEventFilter;
  };

  estimateGas: {
    couponContract(overrides?: CallOverrides): Promise<BigNumber>;

    currentPrice(token: string, overrides?: CallOverrides): Promise<BigNumber>;

    issue(
      inputToken: string,
      amount: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    lockupConfig(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setCouponContract(
      newCouponAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setDependencies(
      couponAddress: string,
      hedgeyAdapterAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setLimits(
      threshold_size: BigNumberish,
      days_multiple: BigNumberish,
      offset: BigNumberish,
      _targetedMintsPerWeek: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setTokenInfo(
      token: string,
      enabled: boolean,
      burnable: boolean,
      startingRate: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setTokensInfo(
      tokens: string[],
      enabled: boolean[],
      burnable: boolean[],
      startingRate: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    stream(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    whitelist(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    couponContract(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    currentPrice(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    issue(
      inputToken: string,
      amount: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    lockupConfig(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setCouponContract(
      newCouponAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setDependencies(
      couponAddress: string,
      hedgeyAdapterAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setLimits(
      threshold_size: BigNumberish,
      days_multiple: BigNumberish,
      offset: BigNumberish,
      _targetedMintsPerWeek: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setTokenInfo(
      token: string,
      enabled: boolean,
      burnable: boolean,
      startingRate: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setTokensInfo(
      tokens: string[],
      enabled: boolean[],
      burnable: boolean[],
      startingRate: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    stream(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    whitelist(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
