/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  CounterSSolCounterScriptAbi,
  CounterSSolCounterScriptAbiInterface,
} from "../CounterSSolCounterScriptAbi";

const _abi = [
  {
    type: "function",
    name: "IS_SCRIPT",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "run",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setUp",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;

export class CounterSSolCounterScriptAbi__factory {
  static readonly abi = _abi;
  static createInterface(): CounterSSolCounterScriptAbiInterface {
    return new utils.Interface(_abi) as CounterSSolCounterScriptAbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CounterSSolCounterScriptAbi {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as CounterSSolCounterScriptAbi;
  }
}
