/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { CounterScript, CounterScriptInterface } from "../CounterScript";

const _abi = [
  {
    type: "function",
    name: "IS_SCRIPT",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "run",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setUp",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;

export class CounterScript__factory {
  static readonly abi = _abi;
  static createInterface(): CounterScriptInterface {
    return new utils.Interface(_abi) as CounterScriptInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CounterScript {
    return new Contract(address, _abi, signerOrProvider) as CounterScript;
  }
}
