/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  CounterJsonAbi,
  CounterJsonAbiInterface,
} from "../CounterJsonAbi";

const _abi = [
  {
    type: "function",
    name: "increment",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "number",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setNumber",
    inputs: [
      {
        name: "newNumber",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;

export class CounterJsonAbi__factory {
  static readonly abi = _abi;
  static createInterface(): CounterJsonAbiInterface {
    return new utils.Interface(_abi) as CounterJsonAbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CounterJsonAbi {
    return new Contract(address, _abi, signerOrProvider) as CounterJsonAbi;
  }
}
