/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  HedgeyTokenLocker,
  HedgeyTokenLockerInterface,
} from "../HedgeyTokenLocker";

const _abi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "flax",
        type: "address",
        internalType: "address",
      },
      {
        name: "hedgey",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "lock",
    inputs: [
      {
        name: "recipient",
        type: "address",
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "durationInDays",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;

export class HedgeyTokenLocker__factory {
  static readonly abi = _abi;
  static createInterface(): HedgeyTokenLockerInterface {
    return new utils.Interface(_abi) as HedgeyTokenLockerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): HedgeyTokenLocker {
    return new Contract(address, _abi, signerOrProvider) as HedgeyTokenLocker;
  }
}
