/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { HedgeyAdapter, HedgeyAdapterInterface } from "../HedgeyAdapter";

const _abi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "flax",
        type: "address",
        internalType: "address",
      },
      {
        name: "hedgey",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "lock",
    inputs: [
      {
        name: "recipient",
        type: "address",
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "durationInDays",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "nft",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "tokenLockupPlan",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract TokenLockupPlans",
      },
    ],
    stateMutability: "view",
  },
] as const;

export class HedgeyAdapter__factory {
  static readonly abi = _abi;
  static createInterface(): HedgeyAdapterInterface {
    return new utils.Interface(_abi) as HedgeyAdapterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): HedgeyAdapter {
    return new Contract(address, _abi, signerOrProvider) as HedgeyAdapter;
  }
}
