/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IERC721TokenReceiverJsonAbi,
  IERC721TokenReceiverJsonAbiInterface,
} from "../IERC721TokenReceiverJsonAbi";

const _abi = [
  {
    type: "function",
    name: "onERC721Received",
    inputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
      {
        name: "",
        type: "address",
        internalType: "address",
      },
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bytes4",
        internalType: "bytes4",
      },
    ],
    stateMutability: "nonpayable",
  },
] as const;

export class IERC721TokenReceiverJsonAbi__factory {
  static readonly abi = _abi;
  static createInterface(): IERC721TokenReceiverJsonAbiInterface {
    return new utils.Interface(_abi) as IERC721TokenReceiverJsonAbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC721TokenReceiverJsonAbi {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IERC721TokenReceiverJsonAbi;
  }
}
