/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { ITilter, ITilterInterface } from "../ITilter";

const _abi = [
  {
    type: "function",
    name: "configure",
    inputs: [
      {
        name: "ref_token",
        type: "address",
        internalType: "address",
      },
      {
        name: "flx",
        type: "address",
        internalType: "address",
      },
      {
        name: "oracle",
        type: "address",
        internalType: "address",
      },
      {
        name: "issuer",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "issue",
    inputs: [
      {
        name: "inputToken",
        type: "address",
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "recipient",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "refValueOfTilt",
    inputs: [
      {
        name: "ref_amount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "preview",
        type: "bool",
        internalType: "bool",
      },
    ],
    outputs: [
      {
        name: "flax_new_balance",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "lpTokens_created",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setEnabled",
    inputs: [
      {
        name: "enabled",
        type: "bool",
        internalType: "bool",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;

export class ITilter__factory {
  static readonly abi = _abi;
  static createInterface(): ITilterInterface {
    return new utils.Interface(_abi) as ITilterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITilter {
    return new Contract(address, _abi, signerOrProvider) as ITilter;
  }
}
