/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { LockupStorage, LockupStorageInterface } from "../LockupStorage";

const _abi = [
  {
    type: "function",
    name: "planBalanceOf",
    inputs: [
      {
        name: "planId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "timeStamp",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "redemptionTime",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "balance",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "remainder",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "latestUnlock",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "planEnd",
    inputs: [
      {
        name: "planId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "end",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "plans",
    inputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "token",
        type: "address",
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "start",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "cliff",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "rate",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "period",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "segmentOriginalEnd",
    inputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "PlanCreated",
    inputs: [
      {
        name: "id",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "recipient",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "start",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "cliff",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "end",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "rate",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "period",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlanRedeemed",
    inputs: [
      {
        name: "id",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "amountRedeemed",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "planRemainder",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "resetDate",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlanSegmented",
    inputs: [
      {
        name: "id",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "segmentId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "newPlanAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newPlanRate",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "segmentAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "segmentRate",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "start",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "cliff",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "period",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newPlanEnd",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "segmentEnd",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlansCombined",
    inputs: [
      {
        name: "id0",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "id1",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "survivingId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "rate",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "start",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "cliff",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "period",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "end",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
] as const;

export class LockupStorage__factory {
  static readonly abi = _abi;
  static createInterface(): LockupStorageInterface {
    return new utils.Interface(_abi) as LockupStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LockupStorage {
    return new Contract(address, _abi, signerOrProvider) as LockupStorage;
  }
}
