/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  MockERC721SolIERC721TokenReceiverAbi,
  MockERC721SolIERC721TokenReceiverAbiInterface,
} from "../MockERC721SolIERC721TokenReceiverAbi";

const _abi = [
  {
    type: "function",
    name: "onERC721Received",
    inputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
      {
        name: "",
        type: "address",
        internalType: "address",
      },
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bytes4",
        internalType: "bytes4",
      },
    ],
    stateMutability: "nonpayable",
  },
] as const;

export class MockERC721SolIERC721TokenReceiverAbi__factory {
  static readonly abi = _abi;
  static createInterface(): MockERC721SolIERC721TokenReceiverAbiInterface {
    return new utils.Interface(
      _abi
    ) as MockERC721SolIERC721TokenReceiverAbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockERC721SolIERC721TokenReceiverAbi {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as MockERC721SolIERC721TokenReceiverAbi;
  }
}
