/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { PyroToken, PyroTokenInterface } from "../PyroToken";

const _abi = [
  {
    type: "function",
    name: "config",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
      {
        name: "",
        type: "address",
        internalType: "address",
      },
      {
        name: "",
        type: "address",
        internalType: "address",
      },
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "redeemRate",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
] as const;

export class PyroToken__factory {
  static readonly abi = _abi;
  static createInterface(): PyroTokenInterface {
    return new utils.Interface(_abi) as PyroTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PyroToken {
    return new Contract(address, _abi, signerOrProvider) as PyroToken;
  }
}
