/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ScriptSolScriptAbi,
  ScriptSolScriptAbiInterface,
} from "../ScriptSolScriptAbi";

const _abi = [
  {
    type: "function",
    name: "IS_SCRIPT",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
] as const;

export class ScriptSolScriptAbi__factory {
  static readonly abi = _abi;
  static createInterface(): ScriptSolScriptAbiInterface {
    return new utils.Interface(_abi) as ScriptSolScriptAbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ScriptSolScriptAbi {
    return new Contract(address, _abi, signerOrProvider) as ScriptSolScriptAbi;
  }
}
