/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { ScriptJsonAbi, ScriptJsonAbiInterface } from "../ScriptJsonAbi";

const _abi = [
  {
    type: "function",
    name: "IS_SCRIPT",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
] as const;

export class ScriptJsonAbi__factory {
  static readonly abi = _abi;
  static createInterface(): ScriptJsonAbiInterface {
    return new utils.Interface(_abi) as ScriptJsonAbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ScriptJsonAbi {
    return new Contract(address, _abi, signerOrProvider) as ScriptJsonAbi;
  }
}
