/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  StringsJsonAbi,
  StringsJsonAbiInterface,
} from "../StringsJsonAbi";

const _abi = [
  {
    type: "error",
    name: "StringsInsufficientHexLength",
    inputs: [
      {
        name: "value",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "length",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
] as const;

export class StringsJsonAbi__factory {
  static readonly abi = _abi;
  static createInterface(): StringsJsonAbiInterface {
    return new utils.Interface(_abi) as StringsJsonAbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): StringsJsonAbi {
    return new Contract(address, _abi, signerOrProvider) as StringsJsonAbi;
  }
}
