/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Tilter, TilterInterface } from "../Tilter";

const _abi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "flx",
        type: "address",
        internalType: "address",
      },
      {
        name: "uniRouter",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "VARS",
    inputs: [],
    outputs: [
      {
        name: "ref_token",
        type: "address",
        internalType: "address",
      },
      {
        name: "factory",
        type: "address",
        internalType: "contract IUniswapV2Factory",
      },
      {
        name: "router",
        type: "address",
        internalType: "contract IUniswapV2Router02",
      },
      {
        name: "flax",
        type: "address",
        internalType: "address",
      },
      {
        name: "oracleSet",
        type: "tuple",
        internalType: "struct ITilter.OracleSet",
        components: [
          {
            name: "flx_ref_token",
            type: "address",
            internalType: "contract IUniswapV2Pair",
          },
          {
            name: "oracle",
            type: "address",
            internalType: "contract Oracle",
          },
        ],
      },
      {
        name: "issuer",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "configure",
    inputs: [
      {
        name: "ref_token",
        type: "address",
        internalType: "address",
      },
      {
        name: "flx",
        type: "address",
        internalType: "address",
      },
      {
        name: "oracle",
        type: "address",
        internalType: "address",
      },
      {
        name: "issuer",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "issue",
    inputs: [
      {
        name: "inputToken",
        type: "address",
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "recipient",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "refValueOfTilt",
    inputs: [
      {
        name: "ref_amount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "preview",
        type: "bool",
        internalType: "bool",
      },
    ],
    outputs: [
      {
        name: "flax_new_balance",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "lpTokens_created",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setEnabled",
    inputs: [
      {
        name: "enabled",
        type: "bool",
        internalType: "bool",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [
      {
        name: "newOwner",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "InputTokenMismatch",
    inputs: [
      {
        name: "inputToken",
        type: "address",
        internalType: "address",
      },
      {
        name: "referenceToken",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "OracleLPsNotSet",
    inputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [
      {
        name: "owner",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "ReentrancyGuardReentrantCall",
    inputs: [],
  },
  {
    type: "error",
    name: "TitlerHasBeenDisabledByOwner",
    inputs: [],
  },
] as const;

export class Tilter__factory {
  static readonly abi = _abi;
  static createInterface(): TilterInterface {
    return new utils.Interface(_abi) as TilterInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Tilter {
    return new Contract(address, _abi, signerOrProvider) as Tilter;
  }
}
