/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { UpdateOracles, UpdateOraclesInterface } from "../UpdateOracles";

const _abi = [
  {
    type: "function",
    name: "IS_SCRIPT",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "run",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;

export class UpdateOracles__factory {
  static readonly abi = _abi;
  static createInterface(): UpdateOraclesInterface {
    return new utils.Interface(_abi) as UpdateOraclesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UpdateOracles {
    return new Contract(address, _abi, signerOrProvider) as UpdateOracles;
  }
}
