/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { URIAdmin, URIAdminInterface } from "../URIAdmin";

const _abi = [
  {
    type: "function",
    name: "baseURI",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "string",
        internalType: "string",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "deleteAdmin",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateBaseURI",
    inputs: [
      {
        name: "_uri",
        type: "string",
        internalType: "string",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "URIAdminDeleted",
    inputs: [
      {
        name: "_admin",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "URISet",
    inputs: [
      {
        name: "newURI",
        type: "string",
        indexed: false,
        internalType: "string",
      },
    ],
    anonymous: false,
  },
] as const;

export class URIAdmin__factory {
  static readonly abi = _abi;
  static createInterface(): URIAdminInterface {
    return new utils.Interface(_abi) as URIAdminInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): URIAdmin {
    return new Contract(address, _abi, signerOrProvider) as URIAdmin;
  }
}
