/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  DraftIERC6093SolIERC1155ErrorsAbi,
  DraftIERC6093SolIERC1155ErrorsAbiInterface,
} from "../DraftIERC6093SolIERC1155ErrorsAbi";

const _abi = [
  {
    type: "error",
    name: "ERC1155InsufficientBalance",
    inputs: [
      {
        name: "sender",
        type: "address",
        internalType: "address",
      },
      {
        name: "balance",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "needed",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "tokenId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "ERC1155InvalidApprover",
    inputs: [
      {
        name: "approver",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "ERC1155InvalidArrayLength",
    inputs: [
      {
        name: "idsLength",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "valuesLength",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "ERC1155InvalidOperator",
    inputs: [
      {
        name: "operator",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "ERC1155InvalidReceiver",
    inputs: [
      {
        name: "receiver",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "ERC1155InvalidSender",
    inputs: [
      {
        name: "sender",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "ERC1155MissingApprovalForAll",
    inputs: [
      {
        name: "operator",
        type: "address",
        internalType: "address",
      },
      {
        name: "owner",
        type: "address",
        internalType: "address",
      },
    ],
  },
] as const;

export class DraftIERC6093SolIERC1155ErrorsAbi__factory {
  static readonly abi = _abi;
  static createInterface(): DraftIERC6093SolIERC1155ErrorsAbiInterface {
    return new utils.Interface(
      _abi
    ) as DraftIERC6093SolIERC1155ErrorsAbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DraftIERC6093SolIERC1155ErrorsAbi {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as DraftIERC6093SolIERC1155ErrorsAbi;
  }
}
