/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  AddressToString,
  AddressToStringInterface,
} from "../AddressToString";

const _abi = [
  {
    type: "function",
    name: "toAsciiString",
    inputs: [
      {
        name: "x",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "",
        type: "string",
        internalType: "string",
      },
    ],
    stateMutability: "pure",
  },
] as const;

export class AddressToString__factory {
  static readonly abi = _abi;
  static createInterface(): AddressToStringInterface {
    return new utils.Interface(_abi) as AddressToStringInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AddressToString {
    return new Contract(address, _abi, signerOrProvider) as AddressToString;
  }
}
